/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gymfinal.glb 
Author: Kristen Brown (https://sketchfab.com/kristnbrown)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modular-gym-86e8cc43d76c44e3925e625fdab155f3
Title: Modular Gym
*/

import { useGLTF } from '@react-three/drei'

export function Gymfinal(props) {
  const { nodes, materials } = useGLTF('./models/gymfinal.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[38.992, 0, 6]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.polySurface1_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
        <mesh geometry={nodes.polySurface2_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
        <mesh geometry={nodes.polySurface3_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface4_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface5_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface6_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface7_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface8_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface9_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface10_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface11_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
        <mesh geometry={nodes.polySurface12_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
        <mesh geometry={nodes.polySurface13_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      </group>
      <mesh geometry={nodes.doorDoors_lambert3SG1_0.geometry} material={materials.lambert3SG1} />
      <mesh geometry={nodes.FloorTile_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile1_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile2_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile3_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile4_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile5_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile6_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile7_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile8_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile9_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile10_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile11_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile12_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile13_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile14_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile15_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile16_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile17_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile18_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile19_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile20_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile21_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile22_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile23_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile24_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile25_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile26_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile27_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile28_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile29_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile30_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile31_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile32_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile33_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile34_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile35_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.WallspillarWall1_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall1_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.WallspillarWall2_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.WallspillarWall3_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.WindowssquareWindow3_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall2_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.WallspillarWall4_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.rectangularWindowWindows1_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall3_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall5_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall6_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall7_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.TV_Mat_TV_0.geometry} material={materials.Mat_TV} />
      <mesh geometry={nodes.Mat_Mat_Mat_0.geometry} material={materials.Mat_Mat} />
      <mesh geometry={nodes.Mat3_Mat_Mat_0.geometry} material={materials.Mat_Mat} />
      <mesh geometry={nodes.Leg_Machine_Mat_LegMachine_0.geometry} material={materials.Mat_LegMachine} />
      <mesh geometry={nodes.Bolt15_SquatRack_0.geometry} material={materials.SquatRack} />
      <mesh geometry={nodes.FloorTile36_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile37_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile38_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile39_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile40_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile41_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile42_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile43_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile44_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile45_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile46_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile47_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile48_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile49_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile50_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile51_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile52_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile53_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Wallswall8_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall9_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.FloorTile54_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile55_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile56_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile57_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile58_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.FloorTile59_Floor_0.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Wallswall10_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Wallswall11_WallsMaterial_0.geometry} material={materials.WallsMaterial} />
      <mesh geometry={nodes.Mat4_Mat_Mat_0.geometry} material={materials.Mat_Mat} />
      <mesh geometry={nodes.Mat5_Mat_Mat_0.geometry} material={materials.Mat_Mat} />
      <mesh geometry={nodes.TV1_Mat_TV_0.geometry} material={materials.Mat_TV} />
      <mesh geometry={nodes.TV2_Mat_TV_0.geometry} material={materials.Mat_TV} />
      <mesh geometry={nodes.treadmill1_Treadmill_lambert3SG1_0.geometry} material={materials.Treadmill_lambert3SG1} />
      <mesh geometry={nodes.treadmill2_Treadmill_lambert3SG1_0.geometry} material={materials.Treadmill_lambert3SG1} />
      <mesh geometry={nodes.Indoor_Bike_Mat_IndoorBike_0.geometry} material={materials.Mat_IndoorBike} />
      <mesh geometry={nodes.Indoor_Bike1_Mat_IndoorBike_0.geometry} material={materials.Mat_IndoorBike} />
      <mesh geometry={nodes.ball12_ball11_0.geometry} material={materials.ball11} />
      <mesh geometry={nodes.ball12_medrack_0.geometry} material={materials.medrack} />
      <mesh geometry={nodes.bench2_bench1_0.geometry} material={materials.bench1} />
      <mesh geometry={nodes.weightScale1_lambert2SG1_0.geometry} material={materials.lambert2SG1} />
      <mesh geometry={nodes.Weight_Bar1_WeightBar_0.geometry} material={materials.WeightBar} />
      <mesh geometry={nodes.pDisc3_papertowel_0.geometry} material={materials.papertowel} />
      <mesh geometry={nodes.Lightswitch1_Lightswich_0.geometry} material={materials.Lightswich} />
      <mesh geometry={nodes.pDisc4_papertowel_0.geometry} material={materials.papertowel} />
      <mesh geometry={nodes.Outlet2_Outlet1_0.geometry} material={materials.Outlet1} />
      <mesh geometry={nodes.Outlet3_Outlet1_0.geometry} material={materials.Outlet1} />
      <mesh geometry={nodes.Outlet4_Outlet1_0.geometry} material={materials.Outlet1} />
      <mesh geometry={nodes.Outlet5_Outlet1_0.geometry} material={materials.Outlet1} />
      <mesh geometry={nodes.pDisc5_papertowel_0.geometry} material={materials.papertowel} />
      <mesh geometry={nodes.weightrackreplacment2pCylinder55_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('./models/gymfinal.glb')
