/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 desk2.glb 
*/
import { useGLTF } from '@react-three/drei'

export function DeskModel(props) {
  const { nodes, materials } = useGLTF('./models/desk2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.36, 0]} scale={1.393}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[8.836, 4.757, -0.132]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.033, 0.024]}>
        <mesh geometry={nodes.Lamp_Bejorama_Cibeles_2142_N290121001_1.geometry} material={materials['clear_window.001']} />
        <mesh geometry={nodes.Lamp_Bejorama_Cibeles_2142_N290121001_2.geometry} material={materials['white_st.003']} />
        <mesh geometry={nodes.Lamp_Bejorama_Cibeles_2142_N290121001_3.geometry} material={materials['st_gold.001']} />
      </group>
      <group position={[-1.797, -0.018, 7.619]} rotation={[Math.PI / 2, 0, -0.622]} scale={26.522}>
        <mesh geometry={nodes.Books_N031016_1.geometry} material={materials.standart_7} />
        <mesh geometry={nodes.Books_N031016_2.geometry} material={materials.standart} />
        <mesh geometry={nodes.Books_N031016_3.geometry} material={materials.standart_6} />
        <mesh geometry={nodes.Books_N031016_4.geometry} material={materials.standart_5} />
        <mesh geometry={nodes.Books_N031016_5.geometry} material={materials.standart_in} />
        <mesh geometry={nodes.Books_N031016_6.geometry} material={materials.standart_11} />
        <mesh geometry={nodes.Books_N031016_7.geometry} material={materials.standart_4} />
        <mesh geometry={nodes.Books_N031016_8.geometry} material={materials.standart_3} />
        <mesh geometry={nodes.Books_N031016_9.geometry} material={materials.standart_2} />
        <mesh geometry={nodes.Books_N031016_10.geometry} material={materials.standart_0} />
        <mesh geometry={nodes.Books_N031016_11.geometry} material={materials.standart_8} />
      </group>
      <group position={[7.699, 2.685, -0.14]} rotation={[Math.PI / 2, 0, 0]} scale={2.801}>
        <mesh geometry={nodes.Selection_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Selection_2.geometry} material={materials['Material.005']} />
      </group>
      <group position={[4.412, 5.865, -0.142]} rotation={[0.001, 0, 1.571]} scale={0.009}>
        <mesh geometry={nodes.Mesh.geometry} material={materials['Material #100']} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials['Material #101']} />
      </group>
      <group position={[4.652, 4.902, -0.09]} rotation={[0.002, 0, 1.57]} scale={0.009}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['Material #119']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Material #118']} />
      </group>
      <group position={[2.284, 5.838, -0.122]} rotation={[0.001, 0, 1.57]} scale={0.009}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials['Material #112']} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials['Material #113']} />
      </group>
      <group position={[2.224, 5.264, -0.089]} rotation={[-0.004, 0, 1.574]} scale={0.009}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials['Material #114']} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials['Material #115']} />
      </group>
      <group position={[4.524, 5.087, -0.12]} rotation={[0.002, 0, 1.57]} scale={0.009}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials['Material #98']} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials['Material #99']} />
      </group>
      <group position={[2.317, 6.064, -0.1]} rotation={[0.001, 0, 1.57]} scale={0.009}>
        <mesh geometry={nodes.Mesh005.geometry} material={materials['Material #97']} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials['Material #96']} />
      </group>
      <group position={[4.541, 5.532, -0.121]} rotation={[0.002, 0, 1.569]} scale={0.009}>
        <mesh geometry={nodes.Mesh006.geometry} material={materials['Material #116']} />
        <mesh geometry={nodes.Mesh006_1.geometry} material={materials['Material #117']} />
      </group>
      <group position={[4.47, 5.707, -0.143]} rotation={[0.002, 0, 1.57]} scale={0.009}>
        <mesh geometry={nodes.Mesh007.geometry} material={materials['Material #110']} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={materials['Material #111']} />
      </group>
      <group position={[2.317, 5.561, -0.146]} rotation={[0, 0, 1.57]} scale={0.009}>
        <mesh geometry={nodes.Mesh008.geometry} material={materials['Material #108']} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials['Material #109']} />
      </group>
      <group position={[4.482, 5.26, -0.12]} rotation={[0.002, 0, 1.57]} scale={0.009}>
        <mesh geometry={nodes.Mesh009.geometry} material={materials['Material #104']} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials['Material #105']} />
      </group>
      <group position={[4.562, 5.393, -0.143]} rotation={[0.002, 0, 1.569]} scale={0.009}>
        <mesh geometry={nodes.Mesh010.geometry} material={materials['Material #106']} />
        <mesh geometry={nodes.Mesh010_1.geometry} material={materials['Material #107']} />
      </group>
      <group position={[2.286, 4.975, -0.09]} rotation={[0, 0, 1.571]} scale={0.009}>
        <mesh geometry={nodes.Mesh011.geometry} material={materials['Material #103']} />
        <mesh geometry={nodes.Mesh011_1.geometry} material={materials['Material #102']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/desk2.glb')
